### ISSUE TITLE
Regression in type propagator or elsewhere for constants

### ISSUE THREAD

**Issue by Fidget-Spinner** [pylbbv/pylbbv#45]
Seems like we can't identify the type of constants anymore,

```python
def f(a, b):
    z = a + b
    return z + 1

for _ in range(64):
    f(1, 1)

>>> dis.dis(f, tier2=True)
  1           0 RESUME_QUICK             0

  2           2 LOAD_FAST                0 (a)
              4 LOAD_FAST                1 (b)
              6 CHECK_FLOAT
              8 NOP
             10 BB_BRANCH_IF_FLAG_SET     0
             16 CHECK_INT
             18 NOP
             20 BB_BRANCH_IF_FLAG_UNSET     0
             26 CHECK_INT
             28 NOP
             30 BB_BRANCH_IF_FLAG_UNSET     0
             36 BINARY_OP_ADD_INT_REST
             38 STORE_FAST               2 (z)
             40 LOAD_FAST                2 (z)
             42 LOAD_CONST               1 (1)
             44 BINARY_OP_ADD_INT        0 (+)
             48 RETURN_VALUE
```

Notice that the second `BINARY_OP_ADD_INT` should be `BINARY_OP_ADD_INT_REST`. This shows either the type prop failed to pass that information or the codegen is borked.

@JuliaPoo

**Comment by JuliaPoo** [comment]
Oh huh interesting ill take a look

**Comment by JuliaPoo** [comment]
Okay for some reason the tier2 is skipping propagating across LOAD_CONST:

```
offset: 6
offset: 6
  [-] Type stack bef: 0
  [-] Type propagating across: LOAD_FAST : 2
  [-] Type stack aft: 1
      Stack: 0000023A9F7AAEC0: [ int->locals[0].int->locals[1]]
      Locals 0000023A9F7AAE90: [ int int int->stack[0]]
offset: 7
offset: 7
offset: 8
offset: 8
  [-] Type stack bef: 2
  [-] Type propagating across: BINARY_OP : 0
  [-] Type stack aft: 1
      Stack: 0000023A9F7AAEC0: [ ?.smallint]
      Locals 0000023A9F7AAE90: [ int int int->locals[0]]
  ```

**Comment by JuliaPoo** [comment]
The reason is because `BINARY_OP_ADD_INT_REST` will not be generated in the presence of a `smallint`, which currently optimises the `BINARY_SUBSC` class of bytecode.

Brings us back to #16 I guess.

@Fidget-Spinner

**Comment by JuliaPoo** [comment]
So I think we shouldn't implement a new opcode like `BINARY_OP_ADD_SMALLINT_REST` because we can't guarantee a `PyLong` can be unboxed into a `smallint`. The other way is to handle `smallint` within `BINARY_OP_ADD_INT_REST` which is detrimental to the performance of said bycode.

**Comment by Fidget-Spinner** [comment]
smallint is only for the BINARY_SUBSCR_LIST_INT_REST its not for the BINARY_OP_* smallint. so we should go ahead and generate BINARY_OP_ADD_INT_REST for smallint (ie treat smallint same as int)

In theory, we can do like Higgs and check `is_int32/64` kind of thing and unbox that accordingly, but it's too much complexity due to overflow checks and rollback you need to do after every int32/64 addition.

**Comment by JuliaPoo** [comment]
Ah so `PySmallInt_Type` functions equivalently to a `PyLong_Type`. I'll work on adding that to `infer_BINARY_OP`
