### ISSUE TITLE
Refactor `infer_xx` in a FSM-style way

### ISSUE THREAD

**Issue by JuliaPoo** [pylbbv/pylbbv#5]
# Feature or enhancement

`infer_xx` to be rewritten in a FSM-style way so that its easier to reason about and potentially allow for syntactic sugar by standardising how these functions are structured.

# Pitch

`infer_xx` is currently difficult to reason about due to multiple logic duplicates and repeated type checks, forced by the almighty structured control flow. But this is C we don't have to restrict ourselves to that! We have **gotos**.

Once [the TYPE_ROOT is represented by a bitmask](https://github.com/pylbbv/pylbbv/issues/4) this can be implemented as a jump table, which is _fast_ and _neat_.

E.g., `infer_BINARY_OP` could look something like this:
```
unknown_unknown:
unknown_long:  
unknown-rawfloat
  type_check(left)
  return
long_unknown:
rawfloat_unknown:
float_unknown:
  type_check(right)  
  return
long_long:
  emit inst
  return
float_float:
  unbox_left
rawfloat_float:
  unbox_right
  goto rawfloat_rawfloat
float_rawfloat:
   unbox_left 
rawfloat_rawfloat: 
  emit inst
  return
default:
  typeguard_failure
```

**Comment by Fidget-Spinner** [comment]
Actually, we don't need 128 bits for this. I realised we can just manually use bits to correspond to different types (we cannot use enums because they are not guaranteed in C to fit in 32 bits), then 64-bits is enough to mask the first 32 types, then the next 32 can be used to indicate the negative types.

E.g.
```
#define PYLONG 1
#define PYFLOAT 2
#define PYRAWFLOAT 3
...

PyTypeObject *
int_to_type(int x)
{
switch(x) {
    case PYLONG:
        return PyLong_Type
...
}
}
```

**Comment by JuliaPoo** [comment]
I should link #4 as this will enable `infer_xx` to be refactored into a jump table.
