### ISSUE TITLE
`BB_TEST_ITER_X` Stencil is invalid

### ISSUE THREAD

**Issue by JuliaPoo** [pylbbv/pylbbv#55]
Annoyingly it performs

```
JUMPBY(INLINE_CACHE_ENTRIES_FOR_ITER);
DISPATCH();
```
Which are invalid in our new CPS stencils. There might be other invalid stencils

**Comment by Fidget-Spinner** [comment]
we can just refactor to make it jump to the end of the body

**Comment by JuliaPoo** [comment]
ye tho i intend to later go through every stencil to find invalid stuff, but im not free as of right now

**Comment by Fidget-Spinner** [comment]
Wait actually, it's supposed to exit the trace when it hits that. Because BB_TEST_ITER_X is a branch. So we are not supposed to compile those either.
